# adapted from https://gist.github.com/m516/550faa3a080c6c2d5daadc4678d81a79

name: Build and Deploy LaTeX Project

permissions: write-all

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Setup LaTeX environment 
      - name: Install TeXLive
        run: |
          sudo apt update
          sudo apt install texlive-full
          
      # Build PDF (run multiple times to create indexes)
      - name: Build PDF
        run: |
          pdflatex AuFS.tex
          pdflatex AuFS.tex
          pdflatex AuFS.tex
  
      # Uploads the PDF
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: AuFS.pdf

      # Publishes the PDF as a release
      - name: Publish PDF
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}-${{ github.run_number }}
          files: AuFS.pdf
          generate_release_notes: true
          make_latest: true
